system("make integration-need", ignore.stdout = TRUE)
if (dir.exists('~/cache'))
  file.copy('~/cache', 'knitr-examples/', recursive = TRUE)
owd = getwd()
covr::coveralls(code = sprintf('\nsetwd("%s"); system("make integration-run", intern = TRUE)', owd))
if (dir.exists('knitr-examples/cache'))
  file.copy('knitr-examples/cache', '~/', recursive = TRUE)
