system("make integration-need", ignore.stdout = TRUE)
if (dir.exists('~/cache'))
  file.copy('~/cache', 'knitr-examples/', recursive = TRUE)
system("make integration-run")
covr::coveralls(code = '\nsystem("make integration-run")')
if (dir.exists('knitr-examples/cache'))
  file.copy('knitr-examples/cache', '~/', recursive = TRUE)
