#' Generate BibTeX bibliography databases for R packages
#'
#' A wrapper function of `xfun::pkg_bib()`.
#' @param ...,prefix Arguments passed to [xfun::pkg_bib()].
#' @export
write_bib = function(..., prefix = getOption('knitr.bib.prefix', 'R-')) {
  xfun::pkg_bib(..., prefix = prefix)
}

#' Get the citation keys of R packages for a \samp{nocite} bibliography
#'
#' This function returns the citation keys of the BibTeX entries generated by
#' [write_bib()], which can be used in the `nocite` field of the YAML metadata
#' of an R Markdown document to include package citations in the References
#' without having to cite them explicitly in the text. Unlike [write_bib()],
#' which auto-generates a fixed key (e.g., \samp{R-knitr}) for a package's
#' `Manual` citation, some packages provide additional preferred citations with
#' their own keys, and all of these keys are captured here.
#' @param ... Arguments passed to [write_bib()].
#' @param file The `.bib` file to write the bibliography database to (passed to
#'   [write_bib()] as its `file` argument). Defaults to an empty string, which
#'   means the entries are discarded and only the keys are returned; normally
#'   you want to set it to a `.bib` file that is also declared in the
#'   `bibliography` field of the YAML metadata, so that the entries are actually
#'   available to be cited.
#' @return A character string of the citation keys concatenated by \samp{, },
#'   with each key prefixed by \samp{@@}, e.g., \samp{@@R-knitr, @@R-xfun}. This
#'   is the syntax expected in the `nocite` field.
#' @export
#' @examples
#' # write the entries to a .bib file and get the keys for nocite
#' bib = tempfile(fileext = '.bib')
#' knitr::pkg_bib_nocite('knitr', file = bib)
#' # in an R Markdown document, you could use it in the YAML metadata like this:
#' # ---
#' # bibliography: packages.bib
#' # nocite: '`r knitr::pkg_bib_nocite(c("knitr", "rmarkdown"), file = "packages.bib")`'
#' # ---
pkg_bib_nocite = function(..., file = '') {
  # write_bib() (via xfun::pkg_bib()) echoes the entries to the console when
  # file = ''; since this function is typically called inline (e.g., in the
  # nocite field), route the output to a throwaway file to keep it quiet and
  # return only the keys
  if (!is.character(file) || file == '') {
    file = tempfile(fileext = '.bib'); on.exit(unlink(file), add = TRUE)
  }
  bib_nocite_keys(write_bib(..., file = file))
}

# extract the citation keys from a list of BibTeX entries (the value of
# write_bib()) and format them for the nocite field. Each package maps to one
# or more entries; the key is the token after the entry type and the opening
# brace, e.g., 'R-knitr' in '@Manual{R-knitr,'.
bib_nocite_keys = function(bib) {
  keys = unlist(lapply(bib, function(entry) {
    x = grep('^@[^{]+\\{', entry, value = TRUE)
    sub('^@[^{]+\\{([^,]+),.*$', '\\1', x)
  }), use.names = FALSE)
  paste0('@', keys, collapse = ', ')
}
