name: Build and deploy package site

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@HEAD
        with:
          use-public-rspm: true
      - uses: yihui/actions/setup-r-dependencies@HEAD
        with:
          extra-packages: litedown xfun .
          r-universe: yihui
      - uses: yihui/actions/litedown-site@HEAD
        with:
          site-dir: 'site'
      - name: Deploy to gh-pages
        run: |
          cd site
          git init
          git checkout -b gh-pages
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "deploy site"
          git push -f "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
